from enum import Enum

class Tasks(Enum):
    
    SPATIAL_COORDINATION = "SC_Task"
    SPATIAL_FREE_RECALL = "SFR_Task"
    SPATIAL_INTEGRATION = "SI_Task"
    SPATIAL_MEMORY_UPDATING = "SMU_Task"
    SPATIAL_TASK_SWITCHING = "STS_Task"

    VISUAL_ITEM_RECOGNITION = "VIR_Task"
    VISUAL_SERIAL_RECALL = "VSR_Task"
    VISUAL_SERIAL_RECOGNITION = "VSRec_Task"

    CHANGE_DETECTION = "CD"
    CHANGE_DETECTION_COLOR = "CD_Color_Task"
    CHANGE_DETECTION_ORIENTATION = "CD_Orientation_Task"
    CHANGE_DETECTION_SIZE = "CD_Size_Task"
    CHANGE_DETECTION_GAP = "CD_Gap_Task"
    CHANGE_DETECTION_CONJ = "CD_Conj_Task"

task_id_map = {
    Tasks.SPATIAL_COORDINATION: 0,
    Tasks.SPATIAL_FREE_RECALL: 1,
    Tasks.SPATIAL_INTEGRATION: 2,
    Tasks.SPATIAL_MEMORY_UPDATING: 3,
    Tasks.SPATIAL_TASK_SWITCHING: 4, 

    Tasks.VISUAL_ITEM_RECOGNITION: 5,
    Tasks.VISUAL_SERIAL_RECALL: 6,
    Tasks.VISUAL_SERIAL_RECOGNITION: 7,

    Tasks.CHANGE_DETECTION_COLOR: 8,
    Tasks.CHANGE_DETECTION_ORIENTATION: 9,
    Tasks.CHANGE_DETECTION_SIZE: 10,
    Tasks.CHANGE_DETECTION_GAP: 11,
    Tasks.CHANGE_DETECTION_CONJ: 12,
}


